# Use official Python runtime as a parent image
FROM python:3.10-slim-buster

# Set noninteractive frontend and configure the timezone
ENV DEBIAN_FRONTEND=noninteractive

# Install necessary runtime dependencies
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    tzdata git curl supervisor ffmpeg \
    && ln -fs /usr/share/zoneinfo/America/Los_Angeles /etc/localtime \
    && echo "America/Los_Angeles" > /etc/timezone \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
    
# Install Node.js and npm
RUN curl -sL https://deb.nodesource.com/setup_21.x | bash - && \
apt-get install -y nodejs

# Install Poetry
RUN curl -sSL https://install.python-poetry.org | python3 -

# Add Poetry to PATH
ENV PATH="/root/.local/bin:$PATH"

# Install pipx using pip
RUN pip install pipx

# Add pipx to PATH
ENV PATH="/root/.local/bin:$PATH"

# Copy the application source code into working directory /home/appuser/app
WORKDIR /home/appuser/app
COPY ./ /home/appuser/app/
RUN mkdir -p /home/appuser/app/logs
 
# Create a non-root user and set permissions
RUN useradd -ms /bin/bash appuser && \
    chown -R appuser:appuser /root && \
    chown -R appuser:appuser /usr && \
    chown -R appuser:appuser /home/appuser && \
    chown -R appuser:appuser /home/appuser/app && \
    chown -R appuser:appuser /home/appuser/app/logs

# Switch to the non-root user
USER appuser

# Add pipx bin to PATH for appuser
ENV PATH="/home/appuser/.local/bin:$PATH"

# uncomment if need to rebuild poetry.lock dependencies
# RUN poetry lock && \

# Install dependencies using Poetry
RUN poetry install --no-root

# Install fabric application using pipx
RUN pipx install .

# Expose ports for fabric-api and fabric-webui
EXPOSE 13337
EXPOSE 13338

# Reset the DEBIAN_FRONTEND environment variable
ENV DEBIAN_FRONTEND=dialog

# Copy supervisord configuration
COPY ./docker/supervisord.conf /etc/supervisor/conf.d/supervisord.conf

# Start supervisord application
CMD ["supervisord", "-n", "-c", "/etc/supervisor/conf.d/supervisord.conf"]
